alter table if exists public.users
  add column if not exists auth_user_id uuid unique references auth.users(id) on delete cascade;

create table if not exists public.admin_users (
  admin_id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  admin_email text not null unique,
  full_name text not null,
  pin_code text not null,
  role text not null default 'Administrator',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table if exists public.users
  alter column password_hash drop not null;

create index if not exists idx_users_auth_user_id on public.users(auth_user_id);
create index if not exists idx_admin_users_auth_user_id on public.admin_users(auth_user_id);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users
    where admin_users.auth_user_id = auth.uid()
  );
$$;

grant execute on function public.is_admin() to authenticated;

alter table public.users enable row level security;
alter table public.admin_users enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.status_updates enable row level security;
alter table public.wallet_transactions enable row level security;
alter table public.loyalty_transactions enable row level security;
alter table public.saved_payment_methods enable row level security;
alter table public.guest_orders enable row level security;

drop policy if exists "users_select_own" on public.users;
create policy "users_select_own"
on public.users for select
using (auth.uid() = auth_user_id);

drop policy if exists "users_insert_own" on public.users;
create policy "users_insert_own"
on public.users for insert
with check (auth.uid() = auth_user_id);

drop policy if exists "users_update_own" on public.users;
create policy "users_update_own"
on public.users for update
using (auth.uid() = auth_user_id)
with check (auth.uid() = auth_user_id);

drop policy if exists "users_admin_all" on public.users;
create policy "users_admin_all"
on public.users for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admin_users_select_self_or_admin" on public.admin_users;
create policy "admin_users_select_self_or_admin"
on public.admin_users for select
using (auth.uid() = auth_user_id or public.is_admin());

drop policy if exists "admin_users_admin_all" on public.admin_users;
create policy "admin_users_admin_all"
on public.admin_users for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "orders_select_own" on public.orders;
create policy "orders_select_own"
on public.orders for select
using (
  exists (
    select 1
    from public.users
    where users.user_id = orders.user_id
      and users.auth_user_id = auth.uid()
  )
);

drop policy if exists "orders_insert_registered_or_guest" on public.orders;
create policy "orders_insert_registered_or_guest"
on public.orders for insert
with check (
  user_id is null
  or exists (
    select 1
    from public.users
    where users.user_id = orders.user_id
      and users.auth_user_id = auth.uid()
  )
);

drop policy if exists "orders_admin_all" on public.orders;
create policy "orders_admin_all"
on public.orders for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "order_items_select_own" on public.order_items;
create policy "order_items_select_own"
on public.order_items for select
using (
  exists (
    select 1
    from public.orders
    join public.users on users.user_id = orders.user_id
    where orders.order_id = order_items.order_id
      and users.auth_user_id = auth.uid()
  )
);

drop policy if exists "order_items_insert_any" on public.order_items;
create policy "order_items_insert_any"
on public.order_items for insert
with check (true);

drop policy if exists "order_items_admin_all" on public.order_items;
create policy "order_items_admin_all"
on public.order_items for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "status_updates_select_own" on public.status_updates;
create policy "status_updates_select_own"
on public.status_updates for select
using (
  exists (
    select 1
    from public.orders
    join public.users on users.user_id = orders.user_id
    where orders.order_id = status_updates.order_id
      and users.auth_user_id = auth.uid()
  )
);

drop policy if exists "status_updates_insert_any" on public.status_updates;
create policy "status_updates_insert_any"
on public.status_updates for insert
with check (true);

drop policy if exists "status_updates_admin_all" on public.status_updates;
create policy "status_updates_admin_all"
on public.status_updates for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "wallet_transactions_select_own" on public.wallet_transactions;
create policy "wallet_transactions_select_own"
on public.wallet_transactions for select
using (
  exists (
    select 1
    from public.users
    where users.user_id = wallet_transactions.user_id
      and users.auth_user_id = auth.uid()
  )
);

drop policy if exists "wallet_transactions_insert_own" on public.wallet_transactions;
create policy "wallet_transactions_insert_own"
on public.wallet_transactions for insert
with check (
  exists (
    select 1
    from public.users
    where users.user_id = wallet_transactions.user_id
      and users.auth_user_id = auth.uid()
  )
);

drop policy if exists "wallet_transactions_admin_all" on public.wallet_transactions;
create policy "wallet_transactions_admin_all"
on public.wallet_transactions for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "loyalty_transactions_select_own" on public.loyalty_transactions;
create policy "loyalty_transactions_select_own"
on public.loyalty_transactions for select
using (
  exists (
    select 1
    from public.users
    where users.user_id = loyalty_transactions.user_id
      and users.auth_user_id = auth.uid()
  )
);

drop policy if exists "loyalty_transactions_insert_own" on public.loyalty_transactions;
create policy "loyalty_transactions_insert_own"
on public.loyalty_transactions for insert
with check (
  exists (
    select 1
    from public.users
    where users.user_id = loyalty_transactions.user_id
      and users.auth_user_id = auth.uid()
  )
);

drop policy if exists "loyalty_transactions_admin_all" on public.loyalty_transactions;
create policy "loyalty_transactions_admin_all"
on public.loyalty_transactions for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "saved_payment_methods_select_own" on public.saved_payment_methods;
create policy "saved_payment_methods_select_own"
on public.saved_payment_methods for select
using (
  exists (
    select 1
    from public.users
    where users.user_id = saved_payment_methods.user_id
      and users.auth_user_id = auth.uid()
  )
);

drop policy if exists "saved_payment_methods_insert_own" on public.saved_payment_methods;
create policy "saved_payment_methods_insert_own"
on public.saved_payment_methods for insert
with check (
  exists (
    select 1
    from public.users
    where users.user_id = saved_payment_methods.user_id
      and users.auth_user_id = auth.uid()
  )
);

drop policy if exists "saved_payment_methods_update_own" on public.saved_payment_methods;
create policy "saved_payment_methods_update_own"
on public.saved_payment_methods for update
using (
  exists (
    select 1
    from public.users
    where users.user_id = saved_payment_methods.user_id
      and users.auth_user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.users
    where users.user_id = saved_payment_methods.user_id
      and users.auth_user_id = auth.uid()
  )
);

drop policy if exists "saved_payment_methods_delete_own" on public.saved_payment_methods;
create policy "saved_payment_methods_delete_own"
on public.saved_payment_methods for delete
using (
  exists (
    select 1
    from public.users
    where users.user_id = saved_payment_methods.user_id
      and users.auth_user_id = auth.uid()
  )
);

drop policy if exists "saved_payment_methods_admin_all" on public.saved_payment_methods;
create policy "saved_payment_methods_admin_all"
on public.saved_payment_methods for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "guest_orders_insert_any" on public.guest_orders;
create policy "guest_orders_insert_any"
on public.guest_orders for insert
with check (true);

drop policy if exists "guest_orders_admin_all" on public.guest_orders;
create policy "guest_orders_admin_all"
on public.guest_orders for all
using (public.is_admin())
with check (public.is_admin());

drop trigger if exists set_admin_users_updated_at on public.admin_users;
create trigger set_admin_users_updated_at
before update on public.admin_users
for each row execute function public.set_updated_at();

-- Example seed after creating the admin's Auth user:
-- insert into public.admin_users (auth_user_id, admin_email, full_name, pin_code, role)
-- values ('YOUR-AUTH-USER-ID', 'admin@example.com', 'WDS Admin', '1234', 'Administrator')
-- on conflict (auth_user_id) do update
-- set admin_email = excluded.admin_email,
--     full_name = excluded.full_name,
--     pin_code = excluded.pin_code,
--     role = excluded.role;
