create table if not exists public.users (
  user_id bigint generated by default as identity primary key,
  full_name text not null,
  phone text not null,
  email text not null unique,
  password_hash text not null,
  wallet_balance numeric(10, 2) not null default 0,
  loyalty_points integer not null default 0,
  text_updates boolean not null default true,
  email_updates boolean not null default true,
  allow_saved_card boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.guest_orders (
  guest_order_id bigint generated by default as identity primary key,
  full_name text not null,
  phone text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  order_id bigint generated by default as identity primary key,
  user_id bigint references public.users(user_id) on delete set null,
  guest_order_id bigint references public.guest_orders(guest_order_id) on delete set null,
  service_type text not null,
  appointment_date date not null,
  appointment_time text not null,
  notes text,
  order_status text not null default 'Drop off',
  payment_method text not null,
  payment_status text not null default 'Pending',
  subtotal numeric(10, 2) not null default 0,
  tax numeric(10, 2) not null default 0,
  total numeric(10, 2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  order_item_id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(order_id) on delete cascade,
  item_type text not null,
  quantity integer not null,
  unit_price numeric(10, 2) not null,
  line_total numeric(10, 2) not null,
  created_at timestamptz not null default now()
);

create table if not exists public.status_updates (
  status_update_id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(order_id) on delete cascade,
  status text not null,
  note text,
  updated_by text,
  created_at timestamptz not null default now()
);

create table if not exists public.wallet_transactions (
  wallet_transaction_id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(user_id) on delete cascade,
  order_id bigint references public.orders(order_id) on delete set null,
  transaction_type text not null,
  amount numeric(10, 2) not null,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.loyalty_transactions (
  loyalty_transaction_id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(user_id) on delete cascade,
  order_id bigint references public.orders(order_id) on delete set null,
  points_change integer not null,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.saved_payment_methods (
  payment_method_id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(user_id) on delete cascade,
  card_token text not null,
  card_brand text not null default 'Card',
  last4 text not null,
  is_default boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists idx_orders_user_id on public.orders(user_id);
create index if not exists idx_orders_guest_order_id on public.orders(guest_order_id);
create index if not exists idx_order_items_order_id on public.order_items(order_id);
create index if not exists idx_status_updates_order_id on public.status_updates(order_id);
create index if not exists idx_wallet_transactions_user_id on public.wallet_transactions(user_id);
create index if not exists idx_loyalty_transactions_user_id on public.loyalty_transactions(user_id);
create index if not exists idx_saved_payment_methods_user_id on public.saved_payment_methods(user_id);

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_users_updated_at on public.users;
create trigger set_users_updated_at
before update on public.users
for each row execute function public.set_updated_at();

drop trigger if exists set_orders_updated_at on public.orders;
create trigger set_orders_updated_at
before update on public.orders
for each row execute function public.set_updated_at();
